### PR TITLE
Add Debian 9 support

### PR DESCRIPTION
**Pull request by hdep**
Here is the rework for adding debian 9 support.
Test are ok on my side.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Thanks @hdep !! We really appreciate your contribution. This PR is almost there there though missing a few things. Take a look at PR #193

**Comment by hdep** [comment]
here is metadata.json  but I don't know how to squash...

**Comment by ghoneycutt** [comment]
Thanks! I can handle the squash. We still need the testing bits though, just like what was done in that PR for Ubuntu 18.

**Comment by ghoneycutt** [comment]
@hdep How's it going with the tests? Do you need any help?

**Comment by hdep** [comment]
Hello, I'm using the module with my debian 9 without any issue so far.
Can I do something else ? 

let  me know

**Comment by ghoneycutt** [comment]
Thanks for letting us know it is working. We just need the other bits related to testing as shown in PR #193 to get this merged.

**Comment by ghoneycutt** [comment]
@hdep check out the files that were modified / created in https://github.com/ghoneycutt/puppet-module-pam/pull/193/files

**Comment by hdep** [comment]
Hello @ghoneycutt can you please give me some guidelines to fix those issues ? I'm not sure to understand why it fails.
Thank you !

**Comment by hdep** [comment]
Hi @ghoneycutt I fixed most of the errors, this was painfull :) Can you  check other errors ? seems docker related don't know what happen. thanks

**Comment by ghoneycutt** [comment]
Tests pass! Awesome work!

**Comment by hdep** [comment]
awesome ! Thanks for the help. Do you know when it will get merged ?

**Comment by ghoneycutt** [comment]
I'm going to test this in Vagrant then squash/rebase the commits then merge.

**Pull request closed without merging**
