### PR TITLE
add amazon linux 2 support

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
CC: @mears148

**Comment by ghoneycutt** [comment]
@mears148 looks like the tests and the configs don't match up

**Comment by ghoneycutt** [comment]
Fixes #214

**Comment by ghoneycutt** [comment]
@mears148 looking at this again and it is unclear to me if Amazon Linux 2 uses `pam_password_auth_ac` and `pam_system_auth_ac` as the spec tests show with their filenames or as you specify in the data.

https://github.com/ghoneycutt/puppet-module-pam/pull/229/files#diff-3cad40562c0add610a6492cef06451e4ce7201b60b19c186b28096b0ef0613cb

Could you please clarify what is actually used?

**Comment by mears148** [comment]
> 
> 
> @mears148 looking at this again and it is unclear to me if Amazon Linux 2 uses `pam_password_auth_ac` and `pam_system_auth_ac` as the spec tests show with their filenames or as you specify in the data.
> 
> https://github.com/ghoneycutt/puppet-module-pam/pull/229/files#diff-3cad40562c0add610a6492cef06451e4ce7201b60b19c186b28096b0ef0613cb
> 
> Could you please clarify what is actually used?

I apologize, I missed that. The correct files to be used are system-auth-ac and password-auth-ac as they are referenced by symbolic links from system-auth and password-auth so that the authconfig utility recognizes these are custom configuration files and should not be overwritten.

**Comment by mears148** [comment]
Essentially it should look almost identical to RHEL 7.

**Comment by lduriez** [comment]
Hello guys, I'm really interested in that merge.
I don't know much about travis-ci but if I can help in anything please let me know.

**Comment by lduriez** [comment]
What I understand from the travis-ci is that parameters are missing in spec_helpher.rb for amzn2 (el2) : https://github.com/ghoneycutt/puppet-module-pam/blob/amz2/spec/spec_helper.rb

You should add thing like that to el2 part :
`        :pam_d_login        => 'with_pam_access',
        :pam_d_sshd         => 'with_pam_access',
        :packages           => ['pam', ],
        :files              => [
          { :prefix         => 'pam_',
            :types          => ['system_auth', ],
            :suffix         => '_ac',
            :symlink        => true,
          }, ],`

**Comment by lduriez** [comment]
Hi any news for that ?

**Comment by treydock** [comment]
Replaced by #259

**Comment by ghoneycutt** [comment]
Thank you for your efforts!

Released in v3.10.0

**Pull request closed without merging**
