### PR TITLE
Trusty

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@Aethylred @Phil-Friderici Thank you both!!! Released in v2.15.0

**Comment by Phil-Friderici** [comment]
Thanks gentleman :)

**Comment by Phil-Friderici** [comment]
@ghoneycutt please also update the version number in ./Modulefile

**Comment by ghoneycutt** [comment]
@Phil-Friderici Thanks! Forgot to push everything. Doh!

**Comment by Phil-Friderici** [comment]
@ghoneycutt ...nightshifting...

**Comment by Aethylred** [comment]
Oresome

**Pull request merged**
