### PR TITLE
Add support for Ubuntu 24.04 (noble)

### PR DESCRIPTION
**Pull request by amateo**

### CODE REVIEW

**Comment by xchotard-talentsoft** [comment]
Thanks, but in `data/os/Ubuntu/24.04.yaml` L12-13:
```
pam::pam_d_login_template: pam/login.ubuntu22.erb
pam::pam_d_sshd_template: pam/sshd.ubuntu22.erb
```
Shouldn't refer to ubuntu24 erb files instead?

**Comment by amateo** [comment]
Yes, it should and I thought it was what I commited. I'm going to fix it.

**Comment by amateo** [comment]
Fix it.

**Comment by xchotard-talentsoft** [comment]
@ghoneycutt ? :)

**Comment by absld** [comment]
Any updates on this @ghoneycutt ?

**Comment by ghoneycutt** [comment]
Closing in favor of https://github.com/ghoneycutt/puppet-module-pam/pull/277 as additional work is needed to enable the acceptance testing.

**Comment by ghoneycutt** [comment]
Released in v5.3.0

**Pull request closed without merging**
