### PR TITLE
Added support for the minor release Debian 8.3 (Jessie)

### PR DESCRIPTION
**Pull request by mrodm**
This PR adds basic support for the next minor (8.3) in Debian current stable (Jessie at the moment) following the changes did with 8.2 previously.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Are there any differences between 8.2 and 8.3?

Perhaps we just need to change the matching from using `'8.2'` to `/^8/`

**Comment by mrodm** [comment]
Yes, it could be changed to `/^8/`, I didn't see any differences between these two debian versions.

**Comment by ghoneycutt** [comment]
Right on, are you up to sending a PR?

**Comment by ghoneycutt** [comment]
Thank you!

**Comment by ghoneycutt** [comment]
This is all the same as 8.2. I think we can say that the module supports Debian 8 and leave the minor versions alone. What do you think?

**Comment by mrodm** [comment]
Yes, it could be done. As you say it is the same as in Debian 8.2.
In that case, what should it be done with the new tests added ?

**Comment by ghoneycutt** [comment]
Appreciate all the help. This module supports Debian 8.

**Pull request closed without merging**
