### PR TITLE
Add support por Ubuntu Bionic 18.04

### PR DESCRIPTION
**Pull request by amateo**
This is a rework of #192 (which was a rework of #186), updated to puppet 5 and with platform configuration in data/os/Ubuntu/18.04.yaml.
I have made a new PR because previous had a conflict with `.travis.yml`. I think that because I started with your `v3` branch, that is now merged in `master` could be the problem for me to make something wrong, so I have just made this new PR, started directly from master.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Thanks you for this!! Please update `metadata.json` and squash your commits into one commit. I'll get this tested in a VM and then we'll be good to merge.

**Comment by amateo** [comment]
> Thanks you for this!! Please update `metadata.json` and squash your commits into one commit. I'll get this tested in a VM and then we'll be good to merge.

Done

**Comment by ghoneycutt** [comment]
@amateo Thank you very much for this awesome pull request! I'm closing this PR and opening PR #205 with your commits and a couple more to add Vagrant testing.

**Comment by ghoneycutt** [comment]
Released in v3.1.10

Thank you!

**Pull request closed without merging**
