### PR TITLE
Added support for Debian Jessie (8)

### PR DESCRIPTION
**Pull request by jplana**
This PR adds basic support for Debian current stable (Jessie at the moment), which is quite similar to Ubuntu.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Wow! Very impressive PR, thank you!

Could you add that Debian 8 is supported in the metadata.json file as well as the README.md ?

Are these settings the defaults that you would see with a vanilla install?

**Comment by jplana** [comment]
Thank you for these great modules :-)

I just added the documentation & metadata (I completely forgot about them, sorry). The defaults that I used were taken from a vanilla install, I hope that was the correct approach.

**Comment by ghoneycutt** [comment]
Yes, definitely!

**Comment by ghoneycutt** [comment]
This is great. We take the approach of the vanilla install, so if you use this module you are not surprised.

**Comment by ghoneycutt** [comment]
I squashed your commits into one and released them in v2.21.0

Thanks again!

**Pull request closed without merging**
